---

- set_fact:
    pidfile: /var/run/redis_{{port}}.pid
    logfile: "{{log_dir}}/redis_{{port}}.log"
    configfile: "{{config_dir}}/{{port}}.conf"
    datadir: "{{redis_data_dir}}/{{port}}"
    service_name: redis-{{port}}
  when: redis_nodes|length > 0

- set_fact:
    pidfile: /var/run/redis.pid
    logfile: "{{log_dir}}/redis.log"
    configfile: "{{config_dir}}/redis.conf"
    datadir: "{{redis_data_dir}}"
    service_name: redis
  when: redis_nodes|length == 1

- name: create data directory
  file:
    path: "{{datadir}}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: config file
  template:
    src: redis.conf.j2
    dest: "{{configfile}}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart redis

- name: configure service
  template:
    src: redis.service.j2
    dest: /etc/systemd/system/{{service_name}}.service
    owner: root
    group: root
    mode: 0755
  when: service == 'systemd'

- name: init script
  template:
    src: init_script.j2
    dest: /etc/init.d/{{service_name}}
    owner: root
    group: root
    mode: 0755
  when: service == 'init'

- name: service
  service:
    name: "{{service_name}}"
    state: started
    enabled: yes
